name: SonarCloud

on:
  push:
    branches:
      - master  # Substitua pela branch que deseja monitorar

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '20'  # Substitua pela versão que você está usando

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarCloud Scanner
        run: |
          # Baixa e instala o SonarScanner
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          mv $HOME/sonar-scanner-4.8.0.2856-linux $HOME/sonar-scanner
          echo "SonarScanner instalado em: $HOME/sonar-scanner"
          # Adiciona o SonarScanner ao PATH
          echo "Adicionando o SonarScanner ao PATH"
          echo "$HOME/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Verify SonarScanner installation
        run: |
          # Verifica se o sonar-scanner está disponível
          sonar-scanner --version

      - name: Run SonarCloud analysis
        run: |
          sonar-scanner \
            -Dsonar.organization="lucascarvalhosteffens" \
            -Dsonar.projectKey="LucasCarvalhoSteffens_N2POO" \
            -Dsonar.sources="." \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
